version: 0.2

phases:
  pre_build:
    commands:
      - DEFAULT_PATH=$(pwd)
      - cd /tmp
      - echo "Installing Terraform"
      - curl -o terraform_${TF_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TF_VERSION}_linux_amd64.zip && mv terraform /usr/bin
      - terraform --version
      - python3 -m venv ./venv
      - source ./venv/bin/activate
      - pip install jinja2-cli==0.7.0 Jinja2==3.0.1 MarkupSafe==2.0.1 boto3==1.18.56 requests==2.26.0
      - cd $DEFAULT_PATH/.infrastructure/
      - |
        for f in *.jinja; do jinja2 $f -D region=${TF_BACKEND_REGION} -D provider_region=${REGION} -D bucket=${TF_S3_BUCKET} -D key=${TF_S3_KEY} -D service=${SERVICE} -D tf_version=${TF_VERSION}    >> ./$(basename $f .jinja).tf; done
        for f in *.tf; do echo "\n \n"; echo $f; cat $f; done       
      - ls -ali
      - terraform init -upgrade

  build:
    commands:
      - cp ../../01/imageDetail.json .
      - terraform apply --auto-approve -var-file=imageDetail.json -var "environment=${ENVIRONMENT}" -var 'tags=${TAGS}'
  post_build:
    commands:
      - echo "Post-Build"